### PR TITLE
Header component & react-icons

### LINKED ISSUE #5: Header - visual
- Create header bar
- Add CSS

No need to make Dark/Light mode functional yet, this will be in another issue

image

### PR DESCRIPTION
**Pull request by ChrisCooper0**
Added HTML & CSS for the Header component. I have also installed 'react-icons' as a dependency for use across the site for the other icons (Search, Caret and Left Arrow)

### CODE REVIEW

**Comment by willgarrett64** [comment]
@ChrisCooper0 - Reviewing this just now (good use of my time at work!) and it all looks great. You certainly did that quickly. Thanks for linking the issue too! This will auto-update the kanban board when I merge it.

I like how you went one step further and added the state in for dark mode, even if we don't have the light mode styles yet. 

Also, when reviewing I noticed how all the single quotes have been changed to double, haha. 
image

**Comment by ChrisCooper0** [comment]
> @ChrisCooper0 - Reviewing this just now (good use of my time at work!) and it all looks great. You certainly did that quickly. Thanks for linking the issue too! This will auto-update the kanban board when I merge it.
> 
> I like how you went one step further and added the state in for dark mode, even if we don't have the light mode styles yet.
> 
> Also, when reviewing I noticed how all the single quotes have been changed to double, haha.
> image

Great! I actually took the Nav state directly from another project which uses the same conditional rendering for a mobile menu toggle. This design doesn't have one so is really quite simple.

As for the quotes, I believe that's my Prettier VSCode extension which auto-formats when I save a file. We can install Prettier as a dependency but might be overkill for this project.

**Comment by willgarrett64** [comment]
@ChrisCooper0  Anyway, I've pulled it to my local repo to review and all looks good so will merge now. I think I made a mistake because I pulled the Header branch into my local Main branch and can't seem to get back to Main before your changes haha. Oh well...

**Comment by willgarrett64** [comment]
@ChrisCooper0  - I've messed it up even more! Can you please re-create the pull request. I accidently closed it instead

**Pull request merged**
